### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by toshiossada** [yostane/flutter2-desktop#1]
![image](https://user-images.githubusercontent.com/2637049/114868440-4a472d80-9dcc-11eb-8a22-0d6b2b0ee62d.png)

**Comment by joaobartolot** [comment]
This happens because WSL2 imports the Windows PATH variable along side with the Linux PATH. To solve it I had to create this file `/etc/wsl.conf` inside the linux and add the lines:

```shell
[interop]
appendWindowsPath = false
```
Close all WSL windows
Then restart WSL with `wsl --shutdown`  in PowerShell
Open a new WSL window
Then check your path is shorter now and doesn't include the Windows PATH anymore:
`echo $PATH`
